root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/huhu-api ./cmd/api"
  bin = "tmp/huhu-api"
  delay = 100
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", "sql"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "css", "png", "jpg", "jpeg", "gif", "png"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true

[log]
  time = true
